# Generated by Django 4.2.6 on 2023-12-03 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_special_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='special_user',
        ),
    ]
