# Generated by Django 4.2.6 on 2023-12-03 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0003_remove_userprofile_special_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='special_users',
            field=models.ManyToManyField(blank=True, related_name='special_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
