# Generated by Django 4.2.6 on 2023-12-03 21:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_userprofile_special_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_users',
            field=models.ManyToManyField(blank=True, related_name='selected_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
