# Generated by Django 4.2.6 on 2023-11-30 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0018_useranswer_selected_answer_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_answer_text',
        ),
    ]
