# Generated by Django 4.2.6 on 2023-12-03 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_remove_useranswer_selected_answer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile',null=True),
            preserve_default=False,
        ),
    ]
