# Generated by Django 4.2.6 on 2023-12-03 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_useranswer_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', null=True),
        ),
    ]
