# Generated by Django 4.2.6 on 2023-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_alter_useranswer_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_profile',
        ),
    ]
