# Generated by Django 4.2.6 on 2023-12-03 13:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


def update_user_profile(apps, schema_editor):
    Photo = apps.get_model('photo', 'Photo')
    UserProfile = apps.get_model('accounts', 'UserProfile')

    # 사용할 기본값을 지정해줍니다.
    default_user_profile = UserProfile.objects.first()

    # 기존에 있는 데이터에 대해 기본값을 설정합니다.
    Photo.objects.filter(user_profile=None).update(user_profile=default_user_profile)

class Migration(migrations.Migration):

    dependencies = [

        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile', default=1),
            preserve_default=False,
        ),
        migrations.RunPython(update_user_profile),
    ]
