# Generated by Django 4.2.6 on 2023-12-03 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_alter_photo_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='user_profile',
        ),
    ]
